"""added Google Token table

Revision ID: 0d799dc60535
Revises: 5f9f2916ad30
Create Date: 2025-11-30 17:39:30.392164

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0d799dc60535'
down_revision = '5f9f2916ad30'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('google_token',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('google_sub', sa.String(length=128), nullable=False),
    sa.Column('access_token', sa.Text(), nullable=False),
    sa.Column('refresh_token', sa.Text(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('scopes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'google_sub', name='uq_google_token_user_sub')
    )
    with op.batch_alter_table('google_token', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_google_token_google_sub'), ['google_sub'], unique=False)
        batch_op.create_index(batch_op.f('ix_google_token_user_id'), ['user_id'], unique=False)

    with op.batch_alter_table('tool_counter', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_tool_counter_user_id'), type_='foreignkey')
        batch_op.create_foreign_key(
            batch_op.f('fk_tool_counter_user_id'),
            'user',
            ['user_id'],
            ['id']
       )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tool_counter', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_tool_counter_user_id'), 'user', ['user_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('google_token', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_google_token_user_id'))
        batch_op.drop_index(batch_op.f('ix_google_token_google_sub'))

    op.drop_table('google_token')
    # ### end Alembic commands ###
