"""add failed_login_attempts and suspended columns

Revision ID: 111b7d66ed41
Revises: 6ebe2992566a
Create Date: 2025-10-16 03:27:37.304596

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '111b7d66ed41'
down_revision = '6ebe2992566a'
branch_labels = None
depends_on = None


def upgrade():
    with op.batch_alter_table("user") as batch_op:
        batch_op.add_column(
            sa.Column(
                "failed_login_attempts",
                sa.Integer(),
                nullable=False,
                server_default="0",
            )
        )
        batch_op.add_column(
            sa.Column(
                "suspended",
                sa.Boolean(),
                nullable=False,
                server_default=sa.text("0"),
            )
        )

    with op.batch_alter_table("user") as batch_op:
        batch_op.alter_column("failed_login_attempts", server_default=None)
        batch_op.alter_column("suspended", server_default=None)


    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('suspended')
        batch_op.drop_column('failed_login_attempts')

    # ### end Alembic commands ###
