"""add fullname and role columns

Revision ID: 1e3a296c4ab0
Revises: 8764822d863f
Create Date: 2025-10-14 14:25:50.714215

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "1e3a296c4ab0"
down_revision = "8764822d863f"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("user") as batch_op:
        batch_op.add_column(
            sa.Column(
                "fullname", sa.String(length=50), nullable=False, server_default=""
            )
        )
        batch_op.add_column(
            sa.Column(
                "role", sa.String(length=20), nullable=False, server_default="user"
            )
        )

    with op.batch_alter_table("user") as batch_op:
        batch_op.alter_column("fullname", server_default=None)
        batch_op.alter_column("role", server_default=None)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("user", schema=None) as batch_op:
        batch_op.drop_column("role")
        batch_op.drop_column("fullname")

    # ### end Alembic commands ###
