"""edited Google Token table

Revision ID: 61d006e451d6
Revises: c50516a37d61
Create Date: 2025-11-30 19:24:39.306474

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '61d006e451d6'
down_revision = 'c50516a37d61'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('google_token', schema=None) as batch_op:
        batch_op.drop_column('token_json')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('google_token', schema=None) as batch_op:
        batch_op.add_column(sa.Column('token_json', sa.TEXT(), nullable=True))

    # ### end Alembic commands ###
