"""edited Google Token table

Revision ID: 95c6b281d8c1
Revises: 61d006e451d6
Create Date: 2025-11-30 19:25:27.608695

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '95c6b281d8c1'
down_revision = '61d006e451d6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('google_token', schema=None) as batch_op:
        batch_op.add_column(sa.Column('token_json', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('google_token', schema=None) as batch_op:
        batch_op.drop_column('token_json')

    # ### end Alembic commands ###
