"""edited Google Token table

Revision ID: c50516a37d61
Revises: 0d799dc60535
Create Date: 2025-11-30 19:13:51.967624

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c50516a37d61'
down_revision = '0d799dc60535'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    with op.batch_alter_table('tool_counter', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_tool_counter_user_id'), type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_tool_counter_user_id'), 'user', ['user_id'], ['id'])


    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tool_counter', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_tool_counter_user_id'), type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_tool_counter_user_id'), 'user', ['user_id'], ['id'], ondelete='CASCADE')


    # ### end Alembic commands ###
